import type { LessonArticle } from './article-types';
const uninformed={id:'uninformed',title:'Berkeley CS188：无信息搜索',url:'https://inst.eecs.berkeley.edu/~cs188/textbook/search/uninformed.html',note:'比较 FIFO、统一代价搜索及其成立条件。'};
const informed={id:'informed',title:'Berkeley CS188：启发式搜索',url:'https://inst.eecs.berkeley.edu/~cs188/textbook/search/informed.html',note:'解释 g/h/f、可采纳启发式、一致性与图搜索。'};
const implementation={id:'implementation',title:'Red Blob：从图到寻路代码',url:'https://www.redblobgames.com/pathfinding/a-star/implementation.html',note:'面向初学者的队列、优先队列、路径回溯和状态建模教程。'};
const boardA='. . . .\nH # # F\n. . # .\n. . . .';
const boardASetup='原创 4×4 冻结地图，坐标为 (x,y)，左上角 (0,0)。H=(0,1)，F=(3,1)，障碍为 (1,1),(2,1),(2,2)。只讲静态图，不模拟蛇身。上路 5 步，下方绕路 7 步。';
export const searchArticles:Record<string,LessonArticle>={
 bfs:{
  motivation:['想找最少走几步就能到食物的路线，可以像水波一样向外扩散：先看一步能到哪里，再看两步、三步。广度优先搜索的队列确保较深的一层不能插到较浅层前面。','这里搜索的是一张图。最简单的图把一个格子当节点，把上下左右相邻关系当边；真实蛇的身体会动，因此“静态格子路线最短”与“完整 Snake 决策最好”是两个不同结论。'],
  prerequisites:[{term:'FIFO 队列',explanation:'先进先出。新发现的格子排到队尾，每次从队首取出最早等待的格子。'},{term:'frontier 与 visited',explanation:'frontier 是发现但尚未扩展的候选；访问记录防止同一个格子反复排队。搜索访问不等于真实蛇走过。'},{term:'parent',explanation:'每个新格记录“是谁发现我的”。这些面包屑能从终点一路回到起点，再反转成正向路径。'}],
  mechanism:[{title:'先排队，再扩展，再回溯',paragraphs:['起点入队并标记。弹出队首，检查其四邻居，把未发现的可通行格记入 parent 并排到队尾。在入队时就标记，可以避免多个前驱把同一格重复加入。队列空仍未发现食物，表示这张输入图里没有路径。','到目标后不需要把全部访问格当路线。只沿 parent 从目标往回走，再反转。正式执行时也只把路线第一步交给规则核心，下次观察到新局面后重新决策。'],sourceIds:['implementation','uninformed']},{title:'最少边数的保证，需要等步成本',paragraphs:['每条边代价相同时，按层扩展先找到的目标路线拥有最少步数。若某些格收费 5、其他格收费 1，最少步数不一定最省费用；这正是下一课 Dijkstra 的用途。','有限静态图、常数时间队列和访问检查下，时间 O(V+E)，额外空间 O(V)。四邻网格 V≤N、E≤4V，可近似 O(N)。若每次删除数组首项都整体搬移，教学代码的实际成本会高于理想队列。完整身体配置搜索的 V 则远不止 N 个格子。'],sourceIds:['princeton']},{title:'从静态地图接回真实蛇',paragraphs:['静态图把中间身体冻结，可能忽略未来释放的空间；过早把身体当空地又会给出执行不了的路线。本项目还逐步模拟候选食物路径，并检查食后空间、出口；拥挤或停滞时会尝试有预算的动态身体恢复。','因此页面展示的 BFS 搜索帧只是决策的一部分，总展开计数可能更多。通过这些检查依然不等于所有未来都安全，实际失败与截断仍应记录。']}],
  workedExample:{title:'沿着五层波纹找到上路',setup:boardASetup,diagram:boardA,steps:['第 0 层是 (0,1)。按上、右、下、左生成邻居，第 1 层为 (0,0),(0,2)。','第 2 层为 (1,0),(1,2),(0,3)；第 3 层为 (2,0),(1,3)。','第 4 层为 (3,0),(2,3)；第 5 层包含食物 (3,1)。','从食物反查 parent 得到 (3,1)←(3,0)←(2,0)←(1,0)←(0,0)←(0,1)。反转后是 5 步上路，当前只执行“上”。'],conclusion:'这是按固定邻居顺序独立核对的静态算例。扩展动画中的其他格子只是内部搜索过程，不是蛇真的走过的轨迹。'},
  codeWalkthrough:[{label:'queue.shift() / queue.pop(0)',explanation:'取队首，实现教材中的 FIFO 顺序；示例为可读性使用数组。正式搜索使用更合适的数据结构和预算管理。'},{label:'cost 与 parent',explanation:'记录已知步数和前驱。单位边权 FIFO 下，首次发现已经是最短步数；更差的重复候选被跳过。'},{label:'path.reverse() / path[::-1]',explanation:'先从食物反查到蛇头，再反转；路径包括起点，第一条真正的移动边是路径的前两个格子之间。'},{label:'blocked 与首步反向检查',explanation:'示例冻结中间身体并允许尾格作为候选，首步不能反向。它没有执行完整动态安全验证，不能直接替代正式策略。'}],
  strengths:['等成本图上能清楚解释最少步数，也适合可达区域与距离场。','没有启发式参数，适合作为 A* 等方法的对照。'],
  pitfalls:['把 FIFO 改成栈后不再按层扩展，最少步数保证会消失。','只搜索头格会合并不同身体姿态；同一头坐标并不总有相同未来。','到达食物后的局面没有自动进入最短路目标，可能在吃完后困死。'],
  exercises:[{question:'三步路每步收费 5，五步路每步收费 1，BFS 会偏向哪条？',answer:'BFS 偏向三步路，总费用 15；费用最优是五步路，总费用 5。它优化边数，想优化非负费用应使用 Dijkstra。'},{question:'找到食物路径，为什么真实演示仍可能选择其他动作？',answer:'完整路径可能在动态身体模拟中碰撞，或者食后出口检查失败，也可能预算不足。正式决策包含这些后续检查与回退，静态帧不是全部决策。'}],sources:[uninformed,implementation,{id:'princeton',title:'Princeton：BreadthFirstPaths',url:'https://algs4.cs.princeton.edu/code/javadoc/edu/princeton/cs/algs4/BreadthFirstPaths.html',note:'最少边数路径及 O(V+E) 时间、O(V) 空间说明。'}]
 },
 dijkstra:{
  motivation:['如果每一步都收费 1，少走就省钱。但若某些区域收费更高，就应该比较累计账单，而不只是步数。Dijkstra 总先处理“从起点走到这里，已知费用最低”的候选。','在 Snake 研究里，费用可以表示人为设计的拥挤或靠墙惩罚，但低费用不自动等于低死亡概率。本项目当前静态边的费用都为 1；加权小棋盘只是拓展算例，界面并没有按格修改收费的开关。'],
  prerequisites:[{term:'g：累计代价',explanation:'已经走过的各条边费用之和。单位边权时才与步数相同。'},{term:'最小优先队列',explanation:'谁的 g 最小就先处理谁；不像 FIFO 永远按进入时间排队。'},{term:'松弛',explanation:'发现经过当前格去邻居更便宜，就更新邻居的账单和前驱。这个词只是在描述改进已有估价。'}],
  mechanism:[{title:'发现更便宜的路，就改账本',paragraphs:['起点 g=0，其余视为无穷。弹出最低 g 的候选，对邻居计算 proposal=g(current)+边费用。只有 proposal 更小才更新 g、parent，并把新记录放进队列。','简洁实现允许同一格在堆中有旧记录。弹出时若保存的账单与当前最优 g 不符，就跳过这个过期项。目标应在有效最小账单被弹出时终止，不能第一次看见目标就宣布最优。'],sourceIds:['implementation']},{title:'非负权重与复杂度',paragraphs:['非负边权保证沿路径继续走不会让累计账单突然下降。不要把吃食奖励直接写成负边费用后，还照搬 Dijkstra 的最优性。负权问题需要不同算法和假设。','二叉堆的常见界为 O((V+E)log V)。允许重复入堆的写法可暂存 O(E) 项，写为 O((V+E)log(V+E)) 也更明确。四邻格网 E=O(V)，可简写 O(N log N)。下方数组排序示例便于阅读，并不拥有堆实现的同样开销。'],sourceIds:['princeton']},{title:'本项目中与 BFS 怎样比较',paragraphs:['本项目每条静态边都收费 1，所以按 g 排序和 BFS 按层扩展给出相同最短距离，稳定平局下顺序也一致。得到相同路线不代表 Dijkstra 带来了额外性能收益。','正式策略仍需要动态模拟、空间检查与预算回退。自定义费用即使以后加入，也只改变输入图的目标，无法自动解决食物后的蛇身困局。'],sourceIds:['uninformed']}],
  workedExample:{title:'三步花 11，五步只花 5',setup:'原创 4×2 静态加权图，S=(0,0)，F=(3,0)。走入上排两格各花 5，走入其余格花 1。数字是费用，不是障碍。',diagram:'S 5 5 F\n1 1 1 1',steps:['直接向右三步，累计费用 5+5+1=11。','从起点向下的账单是 1，向右的账单是 5，所以先处理下面。','沿下排前进，累计账单依次是 2、3、4，再向上进入食物，总费用 5。','最终路线为下、右、右、右、上，虽然多走两步，却比直线便宜。'],conclusion:'BFS 会偏好三步，Dijkstra 偏好费用 5 的五步路线。这个加权图解释一般原理；本项目演示及双语代码采用每步费用 1。'},
  codeWalkthrough:[{label:'queue.sort(…g…) / key=(g,order)',explanation:'示例按累计代价排序，同 g 按发现顺序。正式项目用最小堆；示例排序数组用于看清优先级。'},{label:'g=current.g+1',explanation:'这里明确固定每条边费用 1，没有实现上方 5 元地形。若练习改为加权图，应替换为对应边费用。'},{label:'g < cost[n]',explanation:'更低费用才改 parent 并重新入队；过期条目在弹出时过滤，避免拿旧账单继续扩展。'}],
  strengths:['能处理非负的不同移动费用，清楚区分“步数最少”和“模型费用最低”。','不需要设计朝目标的启发式，可作为 A* 的 h=0 基线。'],
  pitfalls:['负边费用破坏标准证明；奖励不能未经转换直接塞进路径费用。','如果所有费用都是 1，堆可能只是额外开销，不应凭名字宣称更好。','固定图上的省钱路线仍可能在动态身体或食后增长下失效。'],
  exercises:[{question:'第一次用费用 12 的路线发现食物，是否立刻停止？',answer:'不能。队列中更便宜的候选可能继续以低于 12 的费用到达食物；应等有效目标项以最小 g 弹出。'},{question:'把加权图所有费用改为 1，BFS 与 Dijkstra 的最短距离有什么差别？',answer:'没有差别，都找到最少步数路线。不同平局实现可能选不同的等长路径，但距离应一致。'}],sources:[uninformed,implementation,{id:'princeton',title:'Princeton：Dijkstra 最短路径',url:'https://algs4.cs.princeton.edu/code/javadoc/edu/princeton/cs/algs4/DijkstraUndirectedSP.html',note:'非负边权和优先队列复杂度说明。'}]
 },
 astar:{
  motivation:['Dijkstra 只看已经花掉多少，Greedy Best-First 只看离目标似乎还剩多少。A* 将这两条线索相加：f=g+h。它比较的是“如果经这个候选去食物，总费用估计是多少”。','h 只改变先查谁，g 仍累计真实模型费用。若把 h 反复加进 g，就把估计当成实际走过的费用了；若把 h 设为 0，则回到 Dijkstra。'],
  prerequisites:[{term:'g、h、f',explanation:'g 是已走代价，h 是剩余代价估计，f=g+h。三者都不是动作概率或生存概率。'},{term:'可采纳启发式',explanation:'h 不高估真实最低剩余费用。单位四邻网格里的曼哈顿距离忽略了障碍，因此是下界。'},{term:'一致性',explanation:'每条边 u→v 都满足 h(u)≤cost(u,v)+h(v)。它把相邻估计联系起来，比只要求目标方向上的下界更强。'}],
  mechanism:[{title:'像 Dijkstra 改账本，用 f 排队',paragraphs:['起点 g=0，优先级为 h(start)。取出 f 最小的候选，跳过过期 g 记录，对每个邻居计算新的 g。更便宜才改 parent，再以新 g+h 入队。有效目标项弹出时回溯。','本项目平局按发现顺序，不额外优先更小 h。有些教程采用 f 相同再比 h，会得到不同的扩展动画；只要规则一致，顺序不同本身并不证明错误。'],sourceIds:['informed']},{title:'什么时候能保证静态最优',paragraphs:['本课有限静态图、非负边权、目标 h=0、h 不高估，并在发现更低 g 时允许重新打开状态，可保证最低费用路线。若永久关闭已扩展状态而不重开，应要求一致启发式。普通单位四邻网格的曼哈顿距离满足一致性。','每步最低费用为 c 时可用 c×曼哈顿距离；传送门、穿边界或更便宜移动会改变下界条件。把距离乘 2 更积极，不能同时不加说明地保留标准 A* 的最优性承诺。'],sourceIds:['informed','cmu']},{title:'快慢和正确建模是两回事',paragraphs:['一致启发式与二叉堆下，常见复杂度为 O((V+E)log V)，状态记录 O(V)，懒更新堆可能额外保留 O(E) 条目。启发式常减少实际展开，却不能说总比 BFS 更快。允许不一致 h 导致反复重开时，也不能照搬每点只扩展一次的界。','A* 不会凭名字理解移动蛇身。即使用完整身体找到了最短吃食路径，目标若只要求吃到食物，也不包括之后的生存。项目额外做动态恢复和出口检查，但晚局碰撞、停滞和预算失败仍是保留的实测边界。']}],
  workedExample:{title:'f 相同，为什么扩展顺序仍可能不同',setup:boardASetup,diagram:boardA,steps:['起点 g=0、h=3、f=3，但正右有障碍，实际最短路线是 5 步，说明 h 是估计下界。','上方 (0,0) 和下方 (0,2) 都是 g=1、h=4、f=5。按上右下左发现，先扩展上方。','上方新发现 (1,0)：g=2、h=3、f=5。下方 (0,2) 更早入队，项目仍先处理下方；若另用“小 h 优先”的平局规则则会先处理 (1,0)。','沿最终上路，(2,0) 的 f=3+2=5，(3,0) 是 4+1=5，食物是 5+0=5。g 增加、h 减少，总估计相同很正常。'],conclusion:'两种平局规则都可能找到 5 步最短路，但访问次序不同。页面使用发现顺序；不要用另一份教程的动画顺序判定它出错。'},
  codeWalkthrough:[{label:'a.g + distance(a.cell,food)',explanation:'这是队列优先级 f；distance 是 h，g 单独存储，不混入未来估计。'},{label:'current.g !== cost.get(current.cell)',explanation:'跳过已经被更好路线替换的旧记录。更低 g 会更新 parent 并再次加入候选。'},{label:'order',explanation:'同 f 按发现顺序排序，方便双语实现与真实搜索顺序核对。'},{label:'search()',explanation:'示例仅求静态路径，排序数组不是正式最小堆，也不包含动态身体安全验证。真实演示调用的是完整策略。'}],
  strengths:['有可信距离下界时，能把搜索集中到更有希望的区域。','g/h/f 可逐格显示，适合解释实际费用与启发式估计的分工。'],
  pitfalls:['高估 h 或改变移动规则后，原有最优性条件可能不成立。','静态最短路保证不等于 Snake 通关保证，食后出口是额外问题。','完整蛇状态数量很大，节点与墙钟预算可能让搜索提前回退。'],
  exercises:[{question:'A 的 g=4,h=2；B 的 g=2,h=5，先扩展谁？',answer:'A 的 f=6，B 的 f=7，因此先 A。不能只看已花费用，也不能只看剩余估计。'},{question:'把 h 全设为 0 还正确吗？为什么不一定更快？',answer:'非负费用条件下仍正确，并退化为 Dijkstra；失去了向目标集中的引导，可能展开更多节点。是否更快还取决于实现与地图，应测量而非按名字判断。'}],sources:[informed,implementation,{id:'cmu',title:'CMU 15-281：搜索课程讲义',url:'https://www.cs.cmu.edu/~15281/coursenotes/search/index.html',note:'交叉核对 A*、一致启发式与图搜索条件。'}]
 },
 'best-first':{
  motivation:['一步贪心直接选择眼前最近的邻格；贪心最佳优先先把所有已发现、尚未扩展的候选存起来，从整个集合里选 h 最小的一个继续搜索。走到障碍前时，其他分支仍可以留在队列里。','Best-first 是一个方法家族，本课特指 Greedy Best-First：排序只看 h。A* 用 g+h。即使两者都用了优先队列，也不代表在优化同一件事。'],
  prerequisites:[{term:'全局 frontier',explanation:'搜索中已发现但没处理的全部候选，不局限于真实蛇头眼前的四邻格。'},{term:'h 的诱导',explanation:'看起来更接近目标的格子优先，但累计绕了多少路没有直接进入优先级。'},{term:'完整性与最优性',explanation:'有路能否找到是一回事，找到的是否最短是另一回事；还要说明图是否有限、是否去重与是否受预算截断。'}],
  mechanism:[{title:'保留其他分支，但只按距离排队',paragraphs:['起点按 h 入队。每次从全部候选中取 h 最小的格子，扩展邻居并记录前驱，到达目标后回溯路线。与一步贪心相比，尚未处理的分支不会因真实蛇尚未选择它们就消失。','一般教学版本可以在首次发现时固定 parent；本项目共用搜索模块还会在更低 g 时改进父路径，但排序仍只看 h。这项实现差别不把它变成 A*，也不恢复最短路保证。'],sourceIds:['redblob']},{title:'平局会改变结果，但不会改变保证',paragraphs:['一个精心选择的平局顺序可能刚好走出最短路，另一个会绕远。最优保证必须对允许的图和搜索情形成立，不能因为某张图找到了 5 步路，就宣称方法总最优。','有限图、发现去重、不丢 frontier 的基础版本，有路最终能找到，时间约 O(E+V log V)、空间 O(V)。无限树、缺少去重、有预算或可重复改进 g 的实现需要单独分析；不能笼统地说永远找得到或永远找不到。'],sourceIds:['ubc','informed']}],
  workedExample:{title:'同一张图，先追近处可能绕成七步',setup:boardASetup+' 为展示反例，本算例特别采用 h 相同则后加入者优先；这不同于项目的发现顺序平局。',diagram:boardA,steps:['起点 h=3，上 (0,0) 与下 (0,2) 的 h 都为 4。后加入的下方先被处理。','接着处理 (1,2)，h=3；再到 (1,3)，h=4，它比仍等待的 (0,0) 后加入，因此继续抢先。','随后 (2,3)[h=3]、(3,3)[h=2]、(3,2)[h=1]、食物 (3,1)[h=0]。','最终路线用了 7 步，而 BFS 能找到 5 步上路。改平局规则可能走上路，但这只是实例结果变化。'],conclusion:'这份反例的路径已独立核算。当前课堂演示使用稳定发现顺序，不应期待它重现特意采用后进先出平局的七步动画。'},
  codeWalkthrough:[{label:'distance(a.cell,food)',explanation:'排序键只有 h，order 用于平局；g 没有加入排序，因此与 A* 的核心差别就在这里。'},{label:'cost / parent',explanation:'项目示例仍记录 g 并接受更短的已发现路线，方便共用模块及回溯；存在这些变量不等于按 g+h 搜索。'},{label:'queue 与 path.reverse()',explanation:'候选集合在内部搜索期间保留多个分支；先找出一条路径，再执行它的第一步，而非每轮搜索扩展都移动真实蛇。'}],
  strengths:['能直观看到启发式怎样把搜索吸向目标。','适合作为 A* 的对照，帮助理解为什么还需要累计代价 g。'],
  pitfalls:['忽略已付代价，可能很快找到一条绕远路线。','墙和狭窄身体夹缝可能误导曼哈顿距离；h 不是空间或食后安全分数。','更少节点或更快都不是普遍保证，预算限制也会终止尚未完成的搜索。'],
  exercises:[{question:'A:g=8,h=1，B:g=2,h=4，两种方法各先选谁？',answer:'Greedy Best-First 选 A，因为 h=1 更小；A* 选 B，因为它的 f=6 小于 A 的 9。'},{question:'为什么它不是“每一步朝食物走”的同义词？',answer:'它在内部维护整个 frontier，可以返回其他等待的分支，找到路线后才执行第一步。一歩贪心只比较眼前邻格，没有保存这些候选路线。'}],sources:[informed,{id:'redblob',title:'Red Blob：Greedy Best-First 与 A*',url:'https://www.redblobgames.com/pathfinding/a-star/introduction.html#heuristic-search',note:'图示比较只用 h 和使用 g+h 的搜索顺序。'},{id:'ubc',title:'UBC：启发式搜索与 frontier',url:'https://www.cs.ubc.ca/~poole/aibook/3e/html/ArtInt3e.Ch3.S6.html',note:'有限图、循环与无限搜索分支条件的进一步说明。'}]
 },
 beam:{
  motivation:['每一步最多三个非反向选择，想十步就可能遇到 3¹⁰=59049 条序列。束搜索每层只留 K 条最有希望的未来，把资源压在少数候选上。省下的是时间和内存，付出的代价是被剪掉的路线不会自动回来。','宽度 K 管同时留几条路线，深度 D 管往前想几步。增加宽度并不能看见视野以外的陷阱；增加深度也不能复活第一层已经剪掉的逃生分支。'],
  prerequisites:[{term:'完整候选状态',explanation:'需要保存身体排列、方向及食物/增长语义，而不只是头坐标。同一头格配不同蛇身，未来可能完全不同。'},{term:'叶评分',explanation:'在前瞻尽头估计候选好坏，可以包含食物进展、出口、距离等；它是设计出的目标，不是通关概率。'},{term:'全层 top K',explanation:'把当前所有保留者的后继放在同一个池子中选前 K 个，不是每个父节点各留 K 个。'}],
  mechanism:[{title:'扩展、去重、评分、剪枝',paragraphs:['最初只有当前状态。每层对所有保留候选枚举合法动作，用真实移动语义生成后继，去掉等价完整状态，再按评分统一保留前 K 个。每个候选记录自己的第一步动作，搜索结束后才知道真实蛇现在该往哪走。','真正的胜利终态应接受，不应为了凑够深度而要求满盘状态继续产生后继。如果候选池空，只说明当前有限剪枝没保留下计划，不能证明原局面无解。'],sourceIds:['cmu-beam']},{title:'教材前瞻与本项目的边界',paragraphs:['本项目默认束宽 24、深度 16，另受节点和时间限制；在当前食物处停止展开，不读取下一颗食物。吃食叶另做即时出口和空间检查，而不是无限延伸到已知的未来食物。','下面 K=2、D=3 的小故事为了分开宽度与深度，明确在吃食后继续一次不生成新食物的出口模拟。它是概念实验，不是声称当前页面可调 K/D，或当前策略逐层行为完全相同。'],sourceIds:['implementation']},{title:'预算与状态复制的成本',paragraphs:['若每个状态最多 b 个后继，模拟与评分成本为 C，每层最多 Kb 个候选，完整排序约需 O(D·K·b·(C+log(Kb)))。复制 L 段身体时 C 至少包含 O(L)，若加洪泛还包含 O(N)。','保留状态的空间约 O(K·b·S)，S 是一份完整状态大小；另存整条轨迹还需历史空间。不能只写 O(K) 却不计算蛇身。扩大 K 通常覆盖更多候选，但评分竞争与平局变化使它不保证每一局都更好。'],sourceIds:['beam-paper']}],
  workedExample:{title:'多留一条路，与多看一步有什么不同',setup:'仍用 5×5 死胡同图。概念实验 K=2、D=3，优先已吃到当前食物，其次离食物更近，平局偏好上方；不生成未来食物，只继续检查出口。',diagram:'. . . . .\n. . . # #\nT b H . F\n. . . # #\n. . . . .',steps:['第一层：右距食物 1，上和下各 3。保留右、上，剪掉下。','第二层：右→右已经吃到食物；上方分支仍未吃到。示范规则保留“右→右”和“上→上”。','第三层：“右→右”没有合法后继，被剔除；上方分支仍可沿空地移动，因此最终执行第一步上。','如果 D=2，尚未看到吃完无出口，可能选右。如果 K=1，第一层已剪掉上，第三层发现死角也无法恢复它。'],conclusion:'K 与 D 解决不同问题。当前项目在食物叶直接检查出口，避免仅因吃食奖励就接受这种立即困死状态；有限视野仍不等于无限安全。'},
  codeWalkthrough:[{label:'prune(candidates,k)',explanation:'双语代码仅演示一层剪枝：按 value 降序，同分按 id 升序，取前 k 个。没有模拟游戏，也没有实现完整束搜索。'},{label:'value=.3,.8,.6；k=2',explanation:'留下 id=1 和 id=2，顺序按 .8、.6；可以改 k 或分数观察剪枝，但这些数字不是项目成绩。'},{label:'真实演示中的根统计',explanation:'来自完整动态搜索，显示最后完成层里各第一步保留数与最佳叶价值，不是动作概率。候选必须携带 first action 才能把最终路线映射回本步。'}],
  strengths:['宽度与深度提供明确资源控制，适合每次决策预算有限的短期规划。','使用真实身体后继，能区分静态头格图无法表达的不同姿态。'],
  pitfalls:['有限剪枝可能丢掉唯一可行路线，所以不保证完整或最优。','短期吃食评分可能让所有候选冲向同一个陷阱。','未来食物未知，不能用真实环境 RNG 偷看后续题目；也不能把搜索深度耗尽算作通关。'],
  exercises:[{question:'K=4，每个候选最多三个后继，一层最多产生几个，再留几个？',answer:'最多产生 12 个，再从整个候选池统一保留 4 个。碰撞、终局和去重会减少实际数量；每个父节点各留 4 个不是固定束宽。'},{question:'D=2 看不到第三步困死，增大 K 能完全替代增加 D 吗？',answer:'不能。更多分支仍只看到两步，需要增加深度或让叶评分显式检查出口。反过来，如果第一层只留错误方向，单纯加深也不能找回已剪掉的分支。'}],sources:[implementation,{id:'cmu-beam',title:'CMU 11-785：Beam Search 教学材料',url:'https://deeplearning.cs.cmu.edu/F22/document/homework/HW4/P2/HW4P2_F22.pdf',note:'保留 K 条候选并逐层剪枝的框架；原材料用于序列生成，这里适配 Snake 完整状态。'},{id:'beam-paper',title:'Best-First Beam Search 原论文',url:'https://direct.mit.edu/tacl/article/doi/10.1162/tacl_a_00346/96473/Best-First-Beam-Search',note:'区分标准分层束搜索与不同扩展顺序的变体。'}]
 }
};
