import type { AgentId } from '../core';
export interface Lesson { id: string; title: string; group: string; agent?: AgentId; intuition: string; steps: string[]; limitation: string; question: string; answer: string; scope: string; }
export const lessons: Lesson[] = [
  { id:'random',title:'Random · 随机',group:'01 / 经典策略',agent:'random',intuition:'不看地图，从上、右、下、左中随机抽一个动作。它是衡量其他策略是否有效的朴素起点。',steps:['独立策略随机流抽取 0–3。','若抽到反向动作，规则核心记录非法动作并沿原方向继续。','动作仍可能撞墙、身体或障碍。'],limitation:'Random 不过滤碰撞，也不保证抽到的方向真正执行。固定种子不等于安全。',question:'抽到蛇头的反方向，会立即掉头吗？',answer:'不会。simulateMove 把非法反向替换为当前方向，并由 Game.step 记录 illegal-action。',scope:'动作抽样构件；显式输入随机数 u，便于两种语言得到同结果。不是项目 Mulberry32 的替代。'},
  { id:'legal-random',title:'LegalRandom · 合法随机',group:'01 / 经典策略',agent:'legal-random',intuition:'先排除这一步一定撞上的方向，再在剩下的动作里随机选择。只看眼前，下一步仍可能被困住。',steps:['共用 simulateMove 计算反向、墙、身体和障碍碰撞。','非增长移动允许进入本步释放的尾格。','合法集合为空时返回当前方向；这不代表能存活。'],limitation:'立即合法 ≠ 长期可存活。概率分布只覆盖当前合法集合。',question:'为什么尾格有时可以进入，有时不可以？',answer:'非吃食物移动会释放尾格；吃食物时身体增长，尾格不释放。',scope:'单步合法动作过滤与抽样；演示身体和尾格规则。'},
  { id:'greedy',title:'Greedy · 贪心',group:'01 / 经典策略',agent:'greedy',intuition:'每一步都选让蛇头更接近食物的方向，使用横向距离加纵向距离，即曼哈顿距离。',steps:['跳过反向，按上、右、下、左检查候选。','最小化下一格到食物的曼哈顿距离。','距离相同时保留最先遇到的方向。'],limitation:'本项目 Greedy 不做碰撞过滤，所以最近的方向可能撞墙、身体或障碍。',question:'食物与蛇之间有障碍，距离下降就代表好动作吗？',answer:'不代表。距离未编码障碍和未来身体占用，贪心可能直接撞上障碍。',scope:'与当前 Greedy 相同的方向评分与平局顺序。'},
  { id:'safe-greedy',title:'SafeGreedy · 安全启发式',group:'01 / 经典策略',agent:'safe-greedy',intuition:'先按食物距离排序合法动作，再模拟一步，看蛇头是否仍能连到尾巴，并估算可达空间。',steps:['对合法候选按距离、方向排序。','模拟身体移动后洪泛填充空格；尾格作为潜在出口。','尾部可达且空间达到阈值才接受；否则使用空间、出口优先的回退策略。'],limitation:'尾部和空间检查是启发式，不是未来安全证明；预算耗尽也会回退。',question:'洪泛得到 20 格空间，就保证能连续走 20 步吗？',answer:'不能。洪泛是静态连通性估计，没有证明动态身体运动、食物增长和方向约束下存在对应轨迹。',scope:'洪泛空间构件；不是完整 SafeGreedy，完整决策由上方真实引擎演示。'},
  { id:'bfs',title:'BFS · 广度优先',group:'02 / 搜索决策',agent:'bfs',intuition:'像水波一样逐层扩散：先看一步可到的格，再看两步可到的格。单位边权下找到静态最短路。',steps:['FIFO 队列保存 frontier；首次发现格子时记父节点和 g。','弹出一个格并扩展四邻格；首步禁止反向。','找到候选路径后，项目继续逐步模拟身体，再检查尾部和空间，必要时回退。'],limitation:'静态最短路 ≠ Snake 安全。搜索把中间身体当固定障碍，允许尾格；动态模拟与空间检查仍只是保守候选验证加启发式。',question:'BFS 找到食物路径后，为什么最终动作还可能不同？',answer:'候选路径可能在动态身体模拟中碰撞，或吃完后空间/尾部检查不通过，也可能耗尽预算；决策会回退。',scope:'冻结网格上的静态 BFS 路径。省略完整蛇路径安全验证；不能当完整 Snake 策略。'},
  { id:'astar',title:'A* · 启发式搜索',group:'02 / 搜索决策',agent:'astar',intuition:'用 g（已经走的距离）加 h（离食物的估计距离）选择下一个探索格。这里 h 是曼哈顿距离。',steps:['frontier 按 f = g + h 取最小，平局按发现顺序。','只有更小 g 才更新父节点，过期堆节点跳过。','和 BFS 共用动态路径模拟、空间检查与回退。'],limitation:'h 对单位四邻静态图是下界，但不包含动态蛇身。A* 不保证比 BFS 更安全，也不保证所有场景扩展更少。',question:'g=3、h=5 时 f 是多少？f 是存活概率吗？',answer:'f=8。它是静态路径长度的估计，不是存活概率。',scope:'静态 A*，用排序数组表达优先队列；项目实际使用最小堆。'},
  { id:'hamiltonian',title:'Hamiltonian · 条件环路',group:'02 / 搜索决策',agent:'hamiltonian',intuition:'提前构造经过每格一次的闭合环，蛇始终沿环前进，不抄近路。身体必须按环的连续顺序初始化。',steps:['要求无障碍、宽高均大于 1、至少一边为偶数。','验证身体连续位于环上，当前方向不违背下一步。','沿环取后继格；不支持时拒绝使用。'],limitation:'标准初始化不一定满足环序。即使环路有效，步数/无进展预算仍可能提前截断，不承诺有限预算内填满。',question:'8×8 无障碍就足够启用环路策略吗？',answer:'还需要 cycle 初始化、身体连续环序以及兼容方向。本演示自动使用有效的 cycle 初态。',scope:'4×4 已知有效环的后继查询；通用环构造与条件验证在真实引擎中。'},
  { id:'encoding',title:'观察编码 · 12 个输入',group:'03 / 学习与证据',intuition:'把绝对棋盘转换为以蛇头方向为参照的特征，让同一种局部情形能在不同位置共享参数。',steps:['0–2：左、直、右下一步碰撞标志。','3–4：食物向前、向右的位移，除以 max(宽,高)。','5–7：左直右到边界距离；8–10：对应连续无占用格数；11：身体长度 / 可用格数。'],limitation:'局部编码丢失完整身体拓扑，不是全状态。直线可用距离排除即将释放的尾格；不会读取未来食物或 RNG。',question:'两个不同棋盘能有相同的 12 个输入吗？',answer:'能。局部投影会丢失信息，相同特征不保证有相同长期安全动作。',scope:'完整 compact-v2 观察编码，固定场景输出与项目 encodeObservation 对照。'},
  { id:'dqn',title:'DQN / Double DQN',group:'03 / 学习与证据',intuition:'网络为左、直、右输出三个 Q 值，用采样经验的目标值纠正当前估计。默认 Double DQN 把选动作和估值分开。',steps:['compact-v2：12 → 64 ReLU → 64 ReLU → 3；全部网络参数由 TF.js 训练。','epsilon 探索与推理都使用立即碰撞掩码；经验进入 replay，随机抽批训练。','Double：online 选下一合法动作、target 估值；普通 DQN 取 target 的合法最大值。每 100 次优化更新同步 target。'],limitation:'教学数字不是实时训练曲线。终止不 bootstrap；当前预设截断也不 bootstrap。奖励塑形与验证选择不保证收敛或最优。',question:'online=[2,5,1]、target=[4,3,6]，三动作合法时，Double 与普通 DQN 的下一状态值是什么？',answer:'Double 用 online 选索引 1，再读 target[1]=3；普通 DQN 取 target 最大值 6。奖励 1、gamma=.9 时目标分别为 3.7 和 6.4。',scope:'可运行 TD 目标算例。完整训练流程另列为伪代码，不假装此函数就是训练器。'},
  { id:'ga',title:'GA · 神经进化',group:'03 / 学习与证据',intuition:'让一群不同输出权重在同一组训练种子上比赛，保留精英，从锦标赛胜者产生带变异的下一代。',steps:['当前 compact 预设固定 12→24 正负特征投影；只进化 24×3+3 = 75 个输出系数。存储仍兼容 12→64→64→3 张量。','每代 16 个体、2 精英、每个体 3 局；填充率主导 fitness，失败与效率作微小修正。','默认 crossoverRate=0：不交叉，但仍有锦标赛和真实高斯变异；验证种子选择保存模型。'],limitation:'不是全网络进化。有限种群和 60 秒预算可能只完成少量代；训练冠军不等于独立测试冠军。',question:'默认 crossover=0 是否意味着没有进化？',answer:'不是。选择、精英保留和变异仍然发生；只有父代系数交叉被关闭。',scope:'与项目 individualFitness 相同的适应度计算；完整繁殖流程明确作为伪代码。'},
  { id:'evaluation',title:'独立评估 · 看证据',group:'03 / 学习与证据',intuition:'训练用来更新，验证用来选择，测试用来报告。冻结模型后在共同种子上比较，并保留每局分数和失败原因。',steps:['训练生成种子排除验证与测试集；验证预设 20001–20005，测试 30001–30100。','相同地图、初态、预算和种子；冻结模型不探索、不更新权重。','报告均值、分布、终止/截断和成本，不把最佳一局当整体效果。'],limitation:'反复用测试分数调参会污染测试集。当前历史报告有 30 个开发期种子，不能称全部 100 局完全未见；结论仅适用记录的协议。',question:'用测试集挑最好的 checkpoint 后，还能称它为独立测试吗？',answer:'不能。它已参与选择，相当于验证集；应使用新的未参与调参的数据报告最终表现。',scope:'固定四局教学分数的均值与中位数，非本项目实测成绩。'},
];
