import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
for(const algorithm of ['ppo','imitation'])test(`${algorithm} really trains in Worker, restores and evaluates a frozen student`,async({page},info)=>{
  test.setTimeout(120000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await page.getByRole('button',{name:'训练实验室',exact:true}).click();await page.getByRole('button',{name:'Q-learning / SARSA / PPO / 模仿',exact:true}).click();
  const lab=page.getByTestId('learning-lab');await lab.getByLabel('新学习算法',{exact:true}).selectOption(algorithm);await lab.getByLabel('新学习预算',{exact:true}).selectOption('2000');await lab.getByRole('button',{name:'开始新学习训练',exact:true}).click();
  await expect(lab.getByRole('status')).toContainText('任务完成',{timeout:30000});expect(Number(await lab.locator('.metric').filter({hasText:'优化更新'}).locator('strong').textContent())).toBeGreaterThan(0);expect(Number(await lab.locator('.metric').filter({hasText:'已改变参数'}).locator('strong').textContent())).toBeGreaterThan(0);
  const download=page.waitForEvent('download');await lab.getByRole('button',{name:'导出新学习模型',exact:true}).click();const file=await (await download).path(),model=JSON.parse(readFileSync(file!,'utf8'));expect(model.version).toBe('snake-policy-v1');expect(model.algorithm).toBe(algorithm);expect(model.actor.some((v:number)=>v!==0)).toBe(true);
  await lab.getByRole('button',{name:/评估新学习冻结模型/}).click();await expect(lab.getByTestId('learning-evaluation')).toContainText('20 局',{timeout:30000});
  await lab.screenshot({path:`docs/qa/policy/${info.project.name}-${algorithm}.png`});
  await lab.getByLabel('新学习预算',{exact:true}).selectOption('100000');await lab.getByRole('button',{name:'开始新学习训练',exact:true}).click();await lab.getByRole('button',{name:'暂停新学习',exact:true}).click();await expect(lab.getByRole('status')).toContainText('已暂停');
  const checkpointDownload=page.waitForEvent('download');await lab.getByRole('button',{name:'导出新学习检查点',exact:true}).click();const checkpointFile=await (await checkpointDownload).path(),checkpoint=JSON.parse(readFileSync(checkpointFile!,'utf8'));expect(checkpoint.version).toBe('snake-policy-checkpoint-v1');expect(checkpoint.actorOptimizer.t).toBe(checkpoint.updates);
  await lab.getByRole('button',{name:'保存新学习到本地',exact:true}).click();await expect(lab.getByLabel('本地新学习检查点',{exact:true})).toBeVisible();
  await lab.getByRole('button',{name:'继续新学习',exact:true}).click();await lab.getByRole('button',{name:'停止新学习',exact:true}).click();await expect(lab.getByRole('status')).toContainText('已停止');
  await lab.getByLabel('导入新学习模型或检查点',{exact:true}).setInputFiles(checkpointFile!);await lab.getByRole('button',{name:'恢复新学习检查点',exact:true}).click();await lab.getByRole('button',{name:'暂停新学习',exact:true}).click();await lab.getByRole('button',{name:'停止新学习',exact:true}).click();await expect(lab.getByRole('status')).toContainText('已停止');
  await lab.getByLabel('导入新学习模型或检查点',{exact:true}).setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({...model,actor:[0]}))});await expect(page.getByText(/导入失败/)).toBeVisible();await lab.getByLabel('导入新学习模型或检查点',{exact:true}).setInputFiles(file!);
  await page.getByRole('button',{name:'实验台',exact:true}).click();await page.getByLabel('决策策略',{exact:true}).selectOption('model');for(let i=0;i<4;i++)await page.getByRole('button',{name:'单步',exact:true}).click();await page.getByRole('button',{name:'查看本局回放',exact:true}).click();await expect(page.getByText('当前帧验证一致',{exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);expect(errors).toEqual([]);
});
