import {test,expect} from '@playwright/test';
test('shortcut strategy exposes honest budgets, supports replay and rejects obstacles',async({page},info)=>{
  test.setTimeout(120000);
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');
  await page.getByLabel('决策策略',{exact:true}).selectOption('hamiltonian-shortcut');
  const rules=page.locator('.rule-controls');if(await rules.getAttribute('open')===null)await rules.locator('summary').click();
  await page.getByLabel('棋盘尺寸',{exact:true}).selectOption('20');
  await expect(page.getByText('上限 160,000 步',{exact:true})).toBeVisible();
  await page.getByLabel('充足通关预算（N²）',{exact:true}).uncheck();await expect(page.getByText('上限 5,000 步',{exact:true})).toBeVisible();
  await page.getByLabel('充足通关预算（N²）',{exact:true}).check();await page.getByLabel('棋盘尺寸',{exact:true}).selectOption('8');
  for(let i=0;i<8;i++)await page.getByRole('button',{name:'单步',exact:true}).click();
  await page.getByLabel('运行速度',{exact:true}).fill('30');await page.getByRole('button',{name:'开始运行',exact:true}).click();
  await expect(page.getByText('填满棋盘，胜利！',{exact:true})).toBeVisible({timeout:60000});
  const finalHash=await page.getByTestId('game-lab').locator('.tiny-stats strong[title]').getAttribute('title');
  await page.getByTestId('game-lab').screenshot({path:`docs/qa/shortcut/${info.project.name}-filled.png`});
  await page.getByRole('button',{name:'查看本局回放',exact:true}).click();await expect(page.getByText('当前帧验证一致',{exact:true})).toBeVisible();
  const slider=page.getByLabel('回放进度',{exact:true});await slider.fill((await slider.getAttribute('max'))!);await expect(page.locator('.hash-value')).toHaveText(finalHash!);await expect(page.getByText('filled',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'实验台',exact:true}).click();await page.getByLabel('决策策略',{exact:true}).selectOption('hamiltonian-shortcut');
  const settings=page.locator('.rule-controls');if(await settings.getAttribute('open')===null)await settings.locator('summary').click();
  await page.getByTestId('game-lab').getByLabel(/障碍地图/).check();await expect(page.getByText('当前策略不适用于此棋盘',{exact:true})).toBeVisible();
  await page.getByTestId('game-lab').getByLabel(/障碍地图/).uncheck();
  await expect(page.getByTestId('game-lab').locator('.board-canvas canvas')).toBeVisible();
  await page.getByTestId('game-lab').screenshot({path:`docs/qa/shortcut/${info.project.name}-strategy.png`});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);expect(errors).toEqual([]);
});
