import { useEffect, useRef, useState } from 'react';
import type { AgentId, Snapshot } from '../core/types';
import { EXPERIMENT_VERSION } from '../experiments/types';
import type { BatchResult, BatchWorkerEvent, BatchWorkerRequest, EpisodeRow } from '../experiments/types';
import { exportResultsCSV, exportResultsJSON } from '../experiments';
import { saveRecord } from '../storage';
import { AGENTS } from './GameLab';
import { Board } from '../render/Board';
import { Icon, Metric, Panel, Sparkline, downloadFile, fmt } from './shared';
export function BatchLab({notify}:{notify:(message:string)=>void}){
 const [selected,setSelected]=useState<AgentId[]>(['astar','bfs','safe-greedy','legal-random']);const [count,setCount]=useState(100);const [size,setSize]=useState(8);const [stepBudget,setStepBudget]=useState(2000);const [status,setStatus]=useState('idle');const [progress,setProgress]=useState({completed:0,total:0});const [rows,setRows]=useState<EpisodeRow[]>([]);const [result,setResult]=useState<BatchResult|null>(null);const [snapshot,setSnapshot]=useState<{agentId:AgentId;seed:number;snapshot:Snapshot}|null>(null);
 const worker=useRef<Worker|null>(null);const jobId=useRef('');const seq=useRef(-1);
 useEffect(()=>()=>worker.current?.terminate(),[]);
 const send=(type:'pause'|'resume'|'cancel')=>worker.current?.postMessage({type,jobId:jobId.current,configVersion:EXPERIMENT_VERSION} satisfies BatchWorkerRequest);
 useEffect(()=>{const pause=()=>{if(document.hidden&&status==='running')send('pause');};document.addEventListener('visibilitychange',pause);return()=>document.removeEventListener('visibilitychange',pause);},[status]);
 const start=()=>{
  worker.current?.terminate();const instance=new Worker(new URL('../workers/batch.worker.ts',import.meta.url),{type:'module'});worker.current=instance;jobId.current=crypto.randomUUID();seq.current=-1;setStatus('running');setRows([]);setResult(null);setSnapshot(null);setProgress({completed:0,total:count*selected.length});
  instance.onerror=event=>{setStatus('error');notify(`实验 Worker 出错：${event.message}`);};
  instance.onmessage=(event:MessageEvent<BatchWorkerEvent>)=>{const data=event.data;if(data.jobId!==jobId.current||data.seq<=seq.current)return;seq.current=data.seq;if(data.type==='progress'){setProgress({completed:data.completed,total:data.total});setRows(prev=>[...prev,data.row]);}else if(data.type==='snapshot')setSnapshot(data);else if(data.type==='paused')setStatus('paused');else if(data.type==='resumed')setStatus('running');else if(data.type==='completed'||data.type==='cancelled'){setResult(data.result);setStatus(data.result.status);setRows(data.result.rows);notify(`批量实验${data.result.status==='completed'?'完成':'已停止'}：${data.result.completedEpisodes} 局已记录`);}else if(data.type==='error'){setStatus('error');notify(data.message);}};
  instance.postMessage({type:'start',jobId:jobId.current,configVersion:EXPERIMENT_VERSION,spec:{agents:selected,seeds:Array.from({length:count},(_,i)=>10001+i),config:{width:size,height:size,maxSteps:stepBudget,maxNoFood:500},maxWallMs:300000,budget:{maxNodes:10000,maxMs:20},chunkSteps:64}} satisfies BatchWorkerRequest);
 };
 const active=status==='running'||status==='paused';const toggle=(id:AgentId)=>setSelected(prev=>prev.includes(id)?prev.filter(a=>a!==id):[...prev,id]);
 return <div className="lab-content"><div className="metrics-row"><Metric label="已完成对局" value={`${progress.completed} / ${progress.total}`} detail="按共同种子配对"/><Metric label="样本平均得分" value={rows.length?fmt(rows.reduce((s,r)=>s+r.score,0)/rows.length):'—'} detail="实际完成对局"/><Metric label="规则失败" value={rows.filter(r=>['wall','body','obstacle'].includes(r.reason??'')).length} detail="碰撞与截断分别记录"/><Metric label="实验状态" value={{idle:'就绪',running:'运行中',paused:'暂停',completed:'完成',cancelled:'取消','wall-clock':'预算到期',error:'错误'}[status]} detail="独立 Web Worker"/></div>
 <div className="experiment-layout"><Panel title="制定比较协议" eyebrow="BENCHMARK PROTOCOL"><p className="muted">每个策略使用相同种子集。保留逐局原始数据，让结果可以重新计算。</p><fieldset disabled={active} className="unstyled-fieldset"><div className="agent-checks">{AGENTS.map(agent=><label key={agent.id}><input type="checkbox" checked={selected.includes(agent.id)} onChange={()=>toggle(agent.id)}/><span>{agent.label}<small>{agent.tag}</small></span></label>)}</div><div className="form-grid"><label className="field-label">共同种子数<select value={count} onChange={e=>setCount(Number(e.target.value))}><option value={10}>10 · 快速检查</option><option value={100}>100 · 正式比较</option></select></label><label className="field-label">棋盘尺寸<select value={size} onChange={e=>setSize(Number(e.target.value))}><option value={8}>8 × 8</option><option value={12}>12 × 12</option><option value={20}>20 × 20</option></select></label><label className="field-label">每局步数上限<input type="number" min="100" max="250000" value={stepBudget} onChange={e=>setStepBudget(Number(e.target.value))}/></label><button type="button" onClick={()=>setStepBudget(size**4)}>充足通关预算 N²</button><div className="field-label">墙钟预算<strong className="field-value">5 分钟</strong></div></div></fieldset><p className="notice">Hamiltonian 使用沿环初态，结果另列协议组，不与标准初态作配对差值。低样本量结果只用于功能检查。</p><div className="button-row"><button className="primary" disabled={active||selected.length===0} onClick={start}><Icon name="play" size={16}/>运行 {count*selected.length} 局</button>{active&&<><button onClick={()=>send(status==='paused'?'resume':'pause')}>{status==='paused'?'继续':'暂停'}</button><button onClick={()=>send('cancel')}>取消</button></>}</div><div className="progress-track"><div style={{width:`${progress.total?progress.completed/progress.total*100:0}%`}}/></div></Panel>
 <Panel title="实时抽样" eyebrow="SAMPLED ENVIRONMENT" aside={<span className="badge">无图仿真</span>}>{snapshot?<><div className="sample-board"><Board views={[{observation:snapshot.snapshot,label:snapshot.agentId}]}/></div><p className="muted centered">{snapshot.agentId} · 种子 #{snapshot.seed} · 步数 {snapshot.snapshot.steps}</p></>:<div className="empty-state"><Icon name="batch" size={38}/><h3>等待第一批环境状态</h3><p>计算与绘图分开，界面仅接收抽样快照</p></div>}<Sparkline values={rows.map(row=>row.score)} label="逐局实际得分"/></Panel></div>
 <Panel title="实验结果" eyebrow="EVIDENCE, NOT HYPE" aside={<div className="button-row"><button disabled={!result} onClick={()=>result&&downloadFile('snake-benchmark.json',exportResultsJSON(result))}><Icon name="download" size={15}/>JSON</button><button disabled={!result} onClick={()=>result&&downloadFile('snake-benchmark.csv',exportResultsCSV(result),'text/csv;charset=utf-8')}>CSV</button><button disabled={!result} onClick={()=>{if(result)void saveRecord('result',`benchmark-${Date.now()}`,result).then(()=>notify('实验结果已保存到本浏览器')).catch(err=>notify(String(err)));}}>保存</button></div>}>
 {result?<><div className="table-scroll"><table><thead><tr><th>策略 / 初态</th><th>局数</th><th>平均食物</th><th>中位数</th><th>填充率</th><th>碰撞率</th><th>截断率</th><th>决策 p95</th><th>回退</th></tr></thead><tbody>{result.summaries.map(s=><tr key={`${s.agentId}-${s.protocolId}`}><td><strong>{AGENTS.find(a=>a.id===s.agentId)?.label}</strong><small>{s.initializationGroup==='cycle'?'沿环组':'标准组'}</small></td><td>{s.episodes}</td><td className="accent">{fmt(s.score.mean)}</td><td>{fmt(s.score.median)}</td><td>{(s.fillRate.mean*100).toFixed(1)}%</td><td>{(s.failureRate*100).toFixed(1)}%</td><td>{(s.truncationRate*100).toFixed(1)}%</td><td>{s.decisionLatencyP95Ms.toFixed(2)} ms</td><td>{s.fallbackCount}</td></tr>)}</tbody></table></div>{result.paired.length>0&&<details><summary>配对得分差与 95% 置信区间</summary>{result.paired.map(p=><p className="muted" key={`${p.agentA}-${p.agentB}`}>{p.agentA} − {p.agentB}：{fmt(p.meanDifference)}，{p.ci95?`95% CI [${fmt(p.ci95[0])}, ${fmt(p.ci95[1])}]`:'样本不足'}，n={p.pairs}</p>)}</details>}<p className="fine-print">耗时来自当前设备，前 5 次决策预热不计入延迟统计。超出日志上限的延迟采用有界样本；详见 JSON 元数据。结果不代表跨设备性能排名。</p></>:<div className="empty-state compact"><h3>结果来自运行，不是预填数字</h3><p>开始一次实验后，这里会展示得分分布、失败原因与决策成本</p></div>}
 </Panel></div>;
}
