import {createManagedWorker,type ManagedWorker} from './managed-worker';
import {parsePolicyModel} from '../learning/policy';
import {parsePolicyCheckpoint} from '../learning/policy-trainer';
import {restoreLearning,type LearningModel,type LearningCheckpoint} from '../learning/controller';
import {useEffect,useRef,useState} from 'react';
import {normalizeConfig} from '../core';
import {parseTabularCheckpoint,parseTabularModel,type LearningMetrics} from '../learning/tabular';
import type {LearningCommand,LearningEvent,TabularEvaluation} from '../learning/controller';
import {saveRecord,listRecords,loadRecord,type StoredRecordSummary} from '../storage';
import {Board} from '../render/Board';
import {Panel,Metric,Sparkline,downloadFile} from './shared';
export function LearningLab({notify,onModel,onActive}:{notify:(message:string)=>void;onModel:(model:LearningModel)=>void;onActive:(active:boolean)=>void}){
  const [algorithm,setAlgorithm]=useState<LearningModel['algorithm']>('q-learning'),[seed,setSeed]=useState(7),[budget,setBudget]=useState(50000),[obstacles,setObstacles]=useState(false);
  const [status,setStatus]=useState('idle'),[reason,setReason]=useState(''),[metrics,setMetrics]=useState<LearningMetrics|null>(null),[model,setModel]=useState<LearningModel|null>(null),[evaluation,setEvaluation]=useState<TabularEvaluation|null>(null),[imported,setImported]=useState<LearningCheckpoint|null>(null),[saved,setSaved]=useState<StoredRecordSummary[]>([]),[extend,setExtend]=useState(false);
  const worker=useRef<ManagedWorker|null>(null),job=useRef(''),sequence=useRef(0),saveMode=useRef<'file'|'local'>('file'),input=useRef<HTMLInputElement>(null);
  const [checkpointReady,setCheckpointReady]=useState(false);
  const policy=algorithm==='ppo'||algorithm==='imitation';
  const active=['initializing','running','paused'].includes(status);
  useEffect(()=>onActive(active),[active,onActive]);
  const refresh=()=>{void listRecords('checkpoint').then(rows=>setSaved(rows.filter(r=>r.id.startsWith('learning-')))).catch(e=>notify(String(e)));};
  useEffect(()=>{void listRecords('checkpoint').then(rows=>setSaved(rows.filter(r=>r.id.startsWith('learning-')))).catch(()=>undefined);return()=>worker.current?.terminate();},[]);
  const command=(type:'pause'|'resume'|'cancel'|'checkpoint')=>worker.current?.postMessage({type,jobId:job.current} satisfies LearningCommand);
  useEffect(()=>{const hidden=()=>{if(document.hidden&&status==='running')command('pause');};document.addEventListener('visibilitychange',hidden);return()=>document.removeEventListener('visibilitychange',hidden);},[status]);
  const attach=()=>{
    setCheckpointReady(false);worker.current?.terminate();const w=createManagedWorker(()=>new Worker(new URL('../workers/learning.worker.ts',import.meta.url),{type:'module'}),message=>{worker.current=null;setStatus('error');setCheckpointReady(false);setReason(message);notify(message);});worker.current=w;job.current=crypto.randomUUID();sequence.current=0;
    w.onmessage=(e:MessageEvent<LearningEvent>)=>{const d=e.data;if(d.jobId!==job.current||d.sequence<=sequence.current)return;sequence.current=d.sequence;
      if(d.type==='status'){setStatus(d.status);setReason(d.reason??'');}
      if(d.type==='metrics'){setMetrics(d.metrics);setCheckpointReady(true);}
      if(d.type==='model'){setModel(d.model);onModel(d.model);}
      if(d.type==='evaluation')setEvaluation(d.result);
      if(d.type==='checkpoint'){if(saveMode.current==='file')downloadFile(`snake-${d.checkpoint.config.algorithm}-checkpoint.json`,JSON.stringify(d.checkpoint));else void saveRecord('checkpoint',`learning-${d.checkpoint.config.algorithm}-${Date.now()}`,d.checkpoint).then(()=>{notify('新学习检查点已保存在本浏览器');refresh();}).catch(e=>notify(String(e)));}
    };return w;
  };
  const start=()=>{setStatus('initializing');setMetrics(null);setEvaluation(null);setReason('');const w=attach();w.postMessage({type:'start',jobId:job.current,config:{algorithm,seed,maxSteps:budget,maxWallMs:60000,game:normalizeConfig({width:8,height:8,maxSteps:1000,maxNoFood:200,obstacles:obstacles?[18,19,44,45]:[]})}} satisfies LearningCommand);};
  const restore=()=>{if(!imported)return;setStatus('initializing');setEvaluation(null);const w=attach();w.postMessage({type:'restore',jobId:job.current,checkpoint:imported,extraSteps:extend?budget:undefined} satisfies LearningCommand);};
  const read=async(file:File|undefined)=>{if(!file)return;try{if(file.size>10*1024*1024)throw new Error('文件超过 10 MB');const text=await file.text();const raw=JSON.parse(text);if(raw?.version==='snake-tabular-v1'||raw?.version==='snake-policy-v1'){const m=raw.version==='snake-policy-v1'?parsePolicyModel(text):parseTabularModel(text);setModel(m);onModel(m);notify('学习推理模型已验证');}else{const c=raw?.version==='snake-policy-checkpoint-v1'?parsePolicyCheckpoint(text):parseTabularCheckpoint(text);setImported(c);setAlgorithm(c.config.algorithm);notify('学习检查点已验证，可恢复训练');}}catch(e){notify(`导入失败：${String(e)}`);}};
  const evaluate=()=>{if(!model)return;setStatus('initializing');setEvaluation(null);const w=attach();w.postMessage({type:'evaluate',jobId:job.current,model,split:'test'} satisfies LearningCommand);};
  return <div className="lab-content" data-testid="learning-lab"><Panel title={policy?'策略梯度与模仿学习':'表格强化学习'} eyebrow="LEARN FROM EXPERIENCE"><p>{policy?(algorithm==='ppo'?'PPO-Clip 使用真实 rollout、GAE、裁剪策略梯度与 Adam 更新 actor 和 critic。':'模仿学习采集有界 A* 教师的动作，用交叉熵与 Adam 训练独立学生；冻结推理由学生参数独立决策。'):'Q-learning 用下一状态的最大合法 Q 值；SARSA 用实际采样的下一动作。二者通过交互经验更新 Q 表，并用 Q 值独立决策。'}</p>
    <fieldset disabled={active} className="unstyled-fieldset"><div className="form-grid"><label className="field-label">学习算法<select aria-label="新学习算法" value={algorithm} onChange={e=>setAlgorithm(e.target.value as LearningModel['algorithm'])}><option value="q-learning">Q-learning</option><option value="sarsa">SARSA</option><option value="ppo">PPO-Clip</option><option value="imitation">模仿学习 · A* 教师</option></select></label><label className="field-label">种子<input aria-label="新学习种子" type="number" min={0} value={seed} onChange={e=>setSeed(Number(e.target.value))}/></label><label className="field-label">预算<select aria-label="新学习预算" value={budget} onChange={e=>setBudget(Number(e.target.value))}><option value={2000}>2,000 步 · 检查</option><option value={10000}>10,000 步</option><option value={50000}>50,000 步</option><option value={100000}>100,000 步</option></select></label></div><label className="check-label"><input type="checkbox" checked={obstacles} onChange={e=>setObstacles(e.target.checked)}/>新学习障碍地图</label></fieldset>
    {policy?<p className="notice">8×8；12 特征 + 偏置的线性 softmax actor（39 参数）与线性 critic（13 参数）。rollout 128、4 epochs、batch 32；PPO γ=.99、λ=.95、clip=.2、entropy=.01。每次最多60秒；每局1000步／无食物200步。适合观察策略梯度过程；长局效果受局部观察与线性容量限制。</p>:<p className="notice">8×8；5,832 个离散局部状态 × 3 相对动作，α=0.2、γ=0.95，ε 从 1 降至 0.05。立即碰撞过滤，终止和截断不 bootstrap。局部编码会合并不同的身体布局，长局决策存在观察盲区。每次训练最多 60 秒，每局 1,000 步／无食物 200 步。</p>}
    <div className="button-row"><button className="primary" disabled={active} onClick={start}>开始新学习训练</button>{active&&<><button onClick={()=>command(status==='paused'?'resume':'pause')}>{status==='paused'?'继续新学习':'暂停新学习'}</button><button onClick={()=>command('cancel')}>停止新学习</button></>}</div><p role="status">{{idle:'准备就绪',initializing:'初始化',running:'训练或评估中',paused:'已暂停',completed:'任务完成',cancelled:'已停止',error:'任务错误'}[status]}{reason&&` · ${{'step-budget':'达到步数预算','time-budget':'达到时间预算',evaluation:'独立评估完成','evaluation-time-budget':'评估时间预算用尽'}[reason]??reason}`}</p>
  </Panel><div className="metrics-row"><Metric label="学习样本" value={metrics?.samples??0}/><Metric label={policy?'优化更新':'表格更新'} value={metrics?.updates??0}/><Metric label={policy?'已改变参数':'已改变表项'} value={metrics?.changedEntries??0}/><Metric label={algorithm==='imitation'?'教师轨迹平均食物':'训练平均食物'} value={(metrics?.meanScore??0).toFixed(2)}/></div>
  <Panel title="实际学习记录"><Sparkline values={metrics?.curve.map(x=>x.meanScore)??[]} label="新学习曲线"/><p>{policy?'最近策略损失':'最近更新平方量'} {(metrics?.loss??0).toFixed(6)} · {policy?(algorithm==='ppo'?'训练按 softmax 概率采样':'教师轨迹监督训练'):`ε ${(metrics?.epsilon??1).toFixed(3)}`} · 用时 {((metrics?.elapsedMs??0)/1000).toFixed(1)} 秒</p>{metrics&&<div className="training-snapshot"><Board views={[{observation:metrics.snapshot,label:'真实训练采样'}]}/></div>}{metrics?.policy&&<p>价值损失 {metrics.policy.valueLoss.toFixed(4)} · 策略熵 {metrics.policy.entropy.toFixed(4)} · 裁剪比例 {metrics.policy.clipFraction.toFixed(3)} · {metrics.policy.phase==='collect'?'采样阶段':'优化阶段'} · 缓冲 {metrics.policy.bufferSize} 项</p>}<p className="muted">参数变化记录学习进度；独立测试衡量冻结模型效果。模仿学习曲线展示教师轨迹，学生效果见下方独立评估。模型保存最终参数，测试集仅用于评估。</p></Panel>
  <Panel title="新学习模型与检查点"><div className="button-row"><button disabled={!checkpointReady||status==='initializing'} onClick={()=>{saveMode.current='file';command('checkpoint');}}>导出新学习检查点</button><button disabled={!checkpointReady||status==='initializing'} onClick={()=>{saveMode.current='local';command('checkpoint');}}>保存新学习到本地</button><button disabled={!model||active} onClick={()=>model&&downloadFile(`snake-${model.algorithm}-model.json`,JSON.stringify(model))}>导出新学习模型</button><button disabled={active} onClick={()=>input.current?.click()}>导入新学习文件</button></div>
    <input className="sr-only" ref={input} type="file" accept=".json,application/json" aria-label="导入新学习模型或检查点" onChange={e=>{const file=e.target.files?.[0];e.target.value='';void read(file);}}/>
    {saved.length>0&&<label className="field-label">本地学习检查点<select aria-label="本地新学习检查点" disabled={active} defaultValue="" onChange={e=>{if(e.target.value)void loadRecord('checkpoint',e.target.value).then(value=>{const c=restoreLearning(value as LearningCheckpoint).checkpoint();setImported(c);setAlgorithm(c.config.algorithm);notify('已载入学习检查点');}).catch(e=>notify(String(e)));}}><option value="">选择记录</option>{saved.map(r=><option key={r.id} value={r.id}>{r.id}</option>)}</select></label>}
    {imported&&<><label className="check-label"><input type="checkbox" checked={extend} onChange={e=>setExtend(e.target.checked)}/>恢复时追加 {budget} 步／60 秒</label><button disabled={active} onClick={restore}>恢复新学习检查点</button></>}
    <p className="muted">检查点保存参数、随机流、当前身体、SARSA 待执行动作或 PPO rollout／Adam／minibatch 进度。暂停后可保存并精确恢复；停止也保留最近完整状态。文件只接受版本化有限数值，最大 10 MB。已载入模型可用于实验台与竞技。</p>
    <button className="primary" disabled={!model||active} onClick={evaluate}>评估新学习冻结模型 · {model?.seedSplit.testSeeds.length??20} 局</button>{evaluation&&<div data-testid="learning-evaluation"><p>独立 {evaluation.split} · {evaluation.episodes.length} 局 · 平均食物 {evaluation.meanScore.toFixed(2)} · {evaluation.cancelled?'未完成':'完成'}</p><p>通关 {evaluation.episodes.filter(r=>r.reason==='filled').length} · 碰撞 {evaluation.episodes.filter(r=>['wall','body','obstacle'].includes(r.reason??'')).length} · 截断 {evaluation.episodes.filter(r=>['step-limit','no-progress'].includes(r.reason??'')).length}</p><button onClick={()=>downloadFile('snake-learning-evaluation.json',JSON.stringify(evaluation,null,2))}>导出新学习评估</button></div>}
  </Panel></div>;
}
