import { useEffect, useRef, useState } from 'react';
import type { ChangeEvent } from 'react';
import { importReplay, seekReplay, listRecords, loadRecord, exportReplay } from '../storage';
import type { ReplayRecord, StoredRecordSummary } from '../storage';
import { Board } from '../render/Board';
import { Icon, Metric, Panel, downloadFile } from './shared';
export function ReplayLab({replay,onReplay,notify}:{replay:ReplayRecord|null;onReplay:(value:ReplayRecord)=>void;notify:(message:string)=>void}){
 const [step,setStep]=useState(0);const [running,setRunning]=useState(false);const [saved,setSaved]=useState<StoredRecordSummary[]>([]);const [error,setError]=useState('');const input=useRef<HTMLInputElement>(null);
 useEffect(()=>{setStep(0);setRunning(false);setError('');},[replay]);
 useEffect(()=>{void listRecords('replay').then(setSaved).catch(err=>setError(String(err)));},[replay]);
 useEffect(()=>{if(!running||!replay)return;const timer=setInterval(()=>setStep(value=>{if(value>=replay.actions.length){setRunning(false);return value;}return value+1;}),150);return()=>clearInterval(timer);},[running,replay]);
 useEffect(()=>{const pause=()=>{if(document.hidden)setRunning(false);};document.addEventListener('visibilitychange',pause);return()=>document.removeEventListener('visibilitychange',pause);},[]);
 const importFile=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];event.target.value='';if(!file)return;try{if(file.size>10*1024*1024)throw new Error('回放超过 10 MB 上限');const value=importReplay(await file.text());onReplay(value);notify(`回放已验证：${value.actions.length} 步哈希全部一致`);}catch(err){notify(`回放导入失败：${String(err)}`);}};
 let state;try{state=replay?seekReplay(replay,Math.min(step,replay.actions.length)):null;}catch(err){state=null;if(!error)queueMicrotask(()=>setError(String(err)));}
 return <div className="lab-content"><div className="configuration-bar"><div><span className="badge">DETERMINISTIC REPLAY</span><span className="muted"> 动作、配置与哈希，重建每一步</span></div><div className="button-row"><button onClick={()=>input.current?.click()}><Icon name="upload" size={16}/>导入回放</button><button disabled={!replay} onClick={()=>replay&&downloadFile('snake-replay.json',exportReplay(replay))}><Icon name="download" size={16}/>导出</button></div><input ref={input} type="file" className="sr-only" accept=".json,application/json" aria-label="导入回放文件" onChange={event=>void importFile(event)}/></div>
 {state&&replay?<><div className="metrics-row"><Metric label="当前步骤" value={`${step} / ${replay.actions.length}`} detail="逐步哈希验证"/><Metric label="食物数量" value={state.score}/><Metric label="原始种子" value={`#${replay.seed}`}/><Metric label="状态哈希" value={<span className="hash-value">{replay.hashes[step]}</span>} detail="当前帧验证一致"/></div><div className="game-layout"><Panel title={replay.label??'已载入回放'} eyebrow="FRAME-BY-FRAME"><div className="board-focus"><Board views={[{observation:state,label:'回放'}]}/></div><div className="playback-controls"><button className="primary" disabled={step>=replay.actions.length} onClick={()=>setRunning(!running)}><Icon name={running?'pause':'play'} size={17}/>{running?'暂停':'播放'}</button><button disabled={running||step===0} onClick={()=>setStep(step-1)}>上一步</button><button disabled={running||step>=replay.actions.length} onClick={()=>setStep(step+1)}>下一步</button><button onClick={()=>{setRunning(false);setStep(0);}}><Icon name="reset" size={16}/></button></div><label className="replay-slider">跳转到第 {step} 步<input aria-label="回放进度" type="range" min="0" max={replay.actions.length} value={Math.min(step,replay.actions.length)} onChange={e=>{setRunning(false);setStep(Number(e.target.value));}}/></label></Panel><aside><Panel title="轨迹信息" eyebrow="VERIFIED RECORD"><dl className="detail-list"><div><dt>核心版本</dt><dd>{replay.coreVersion}</dd></div><div><dt>棋盘</dt><dd>{state.config.width} × {state.config.height}</dd></div><div><dt>初始化</dt><dd>{state.config.initialization}</dd></div><div><dt>动作数</dt><dd>{replay.actions.length}</dd></div><div><dt>终局</dt><dd>{state.reason??'尚未结束'}</dd></div></dl><p className="notice">回放直接执行已记录动作，无需重新运行策略或训练。同种子、同规则、同动作应得到相同哈希。</p></Panel></aside></div></>:<Panel><div className="empty-state large"><Icon name="replay" size={48}/><h2>好决策，值得再看一次</h2><p>从实验台打开当前对局，或导入一份回放文件</p><button className="primary" onClick={()=>input.current?.click()}><Icon name="upload" size={16}/>选择回放文件</button></div></Panel>}
 {error&&<p className="notice error">{error}</p>}<Panel title="本地回放库" eyebrow="SAVED IN THIS BROWSER" aside={<button onClick={()=>void listRecords('replay').then(setSaved).catch(err=>notify(String(err)))}>刷新</button>}>{saved.length===0?<p className="muted">还没有本地回放。在实验台点击“保存回放”即可添加。</p>:<div className="saved-list">{saved.map(item=><button key={item.id} onClick={()=>{void loadRecord<ReplayRecord>('replay',item.id).then(value=>{if(value)onReplay(value);}).catch(err=>notify(String(err)));}}><Icon name="replay" size={20}/><span><strong>{item.id}</strong><small>{new Date(item.updatedAt).toLocaleString()} · {(item.bytes/1024).toFixed(1)} KB</small></span><Icon name="arrow" size={18}/></button>)}</div>}</Panel></div>;
}
