import {createManagedWorker,type ManagedWorker} from './managed-worker';
import { useEffect, useRef, useState } from 'react';
import type { ChangeEvent } from 'react';
import type { EvaluationResult, FrozenModel, TrainingAlgorithm, TrainingCheckpoint, TrainingCommand, TrainingEvent, TrainingMetrics } from '../training/types';
import { parseFrozenModel } from '../training/inference';
import { parseCheckpoint } from '../training/checkpoint';
import { compactTrainingPreset } from '../training/presets';
import { Board } from '../render/Board';
import { saveRecord, listRecords, loadRecord } from '../storage';
import type { StoredRecordSummary } from '../storage';
import { Icon, Metric, Panel, Sparkline, downloadFile, fmt } from './shared';
const REASON_LABELS:Record<string,string>={'environment-step budget':'达到环境步数预算','wall-clock budget':'达到运行时间预算','generation budget':'达到代数预算','cancelled by user; live tensors and replay released':'已停止计算并释放训练内存','frozen test evaluation complete':'独立测试集评估完成','frozen test evaluation, epsilon = 0':'冻结评估 · 关闭探索与更新'};
export function TrainingLab({notify,onModel,onActive}:{notify:(message:string)=>void;onModel:(model:FrozenModel)=>void;onActive?:(active:boolean)=>void}){
 const [algorithm,setAlgorithm]=useState<TrainingAlgorithm>('dqn');const [seed,setSeed]=useState(7);const [budget,setBudget]=useState(100000);const [double,setDouble]=useState(true);const [obstacles,setObstacles]=useState(false);const [status,setStatus]=useState('idle');const [reason,setReason]=useState('');const [metrics,setMetrics]=useState<TrainingMetrics|null>(null);const [model,setModel]=useState<FrozenModel|null>(null);const [evaluation,setEvaluation]=useState<EvaluationResult|null>(null);const [imported,setImported]=useState<TrainingCheckpoint|null>(null);const [saved,setSaved]=useState<StoredRecordSummary[]>([]);const [extend,setExtend]=useState(false);
 const worker=useRef<ManagedWorker|null>(null);const jobId=useRef('');const sequence=useRef(-1);const saveMode=useRef<'file'|'local'>('file');const input=useRef<HTMLInputElement>(null);
 const send=(type:'pause'|'resume'|'cancel'|'checkpoint'|'export-model')=>worker.current?.postMessage({type,jobId:jobId.current} satisfies TrainingCommand);
 const attachWorker=()=>{
  worker.current?.terminate();const instance=createManagedWorker(()=>new Worker(new URL('../workers/training.worker.ts',import.meta.url),{type:'module'}),message=>{worker.current=null;setStatus('error');setReason(message);notify(`训练 Worker 出错：${message}`);});worker.current=instance;jobId.current=crypto.randomUUID();sequence.current=-1;
  instance.onmessage=(event:MessageEvent<TrainingEvent>)=>{const data=event.data;if(data.jobId!==jobId.current||data.sequence<=sequence.current)return;sequence.current=data.sequence;
   if(data.type==='progress')setMetrics(data.metrics);
   else if(data.type==='status'){setStatus(data.status);setReason(REASON_LABELS[data.reason??'']??data.reason??'');}
   else if(data.type==='model'){setModel(data.model);onModel(data.model);}
   else if(data.type==='checkpoint'){if(saveMode.current==='file'){downloadFile(`snake-${data.checkpoint.algorithm}-checkpoint.json`,JSON.stringify(data.checkpoint));notify('完整检查点已导出，包含优化器、随机流与未完成环境');}else void saveRecord('checkpoint',`training-${Date.now()}`,data.checkpoint).then(()=>{notify('检查点已保存在本浏览器');void listRecords('checkpoint').then(rows=>setSaved(rows.filter(r=>!r.id.startsWith('learning-'))));}).catch(err=>notify(String(err)));}
   else if(data.type==='evaluation'){setEvaluation(data.result);setStatus(data.result.cancelled?'cancelled':'completed');notify(`冻结模型测试${data.result.cancelled?'已取消':'完成'}：${data.result.episodes.length} 个独立种子`);}
   else if(data.type==='error'){setStatus('error');setReason(data.message);notify(data.message);}
  };return instance;
 };
 useEffect(()=>{void listRecords('checkpoint').then(rows=>setSaved(rows.filter(r=>!r.id.startsWith('learning-')))).catch(()=>undefined);return()=>worker.current?.terminate();},[]);
 useEffect(()=>{const pause=()=>{if(document.hidden&&(status==='running'||status==='initializing'))send('pause');};document.addEventListener('visibilitychange',pause);return()=>document.removeEventListener('visibilitychange',pause);},[status]);
 const start=()=>{setMetrics(null);setEvaluation(null);setReason('');setStatus('initializing');const instance=attachWorker();const preset=compactTrainingPreset(algorithm,seed,budget);instance.postMessage({type:'start',jobId:jobId.current,algorithm,config:{...preset,game:{...preset.game,obstacles:obstacles?[18,19,44,45]:[]},dqn:{...preset.dqn,doubleDQN:double}}} satisfies TrainingCommand);};
 const resumeCheckpoint=()=>{if(!imported)return;setStatus('initializing');setReason('');const instance=attachWorker();instance.postMessage({type:'import',jobId:jobId.current,checkpoint:extend?{...imported,config:{...imported.config,budget:{...imported.config.budget,maxEnvSteps:imported.config.budget.maxEnvSteps+budget,maxWallMs:imported.config.budget.maxWallMs+60000,maxGenerations:imported.config.budget.maxGenerations+50}}}:imported} satisfies TrainingCommand);};
 const importFile=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];event.target.value='';if(!file)return;try{if(file.size>128*1024*1024)throw new Error('文件超过 128 MB 安全上限');const text=await file.text();const value:unknown=JSON.parse(text);if(typeof value==='object'&&value!==null&&'version'in value&&value.version==='snake-mlp-v1'){const loaded=parseFrozenModel(text);setModel(loaded);onModel(loaded);notify('推理模型已验证并载入，可运行独立评估');}else{const checkpoint=parseCheckpoint(text);setImported(checkpoint);setAlgorithm(checkpoint.algorithm);notify('检查点结构已验证，恢复时将校验优化器、回放与环境');}}catch(err){notify(`导入失败：${String(err)}`);}};
 const evaluate=()=>{if(!model)return;setStatus('initializing');setEvaluation(null);const instance=attachWorker();jobId.current=crypto.randomUUID();sequence.current=-1;instance.postMessage({type:'evaluate',jobId:jobId.current,model,seeds:model.seedSplit.testSeeds} satisfies TrainingCommand);};
 const active=['running','paused','initializing'].includes(status);const total=metrics?.envSteps??0;
 useEffect(()=>onActive?.(active),[active,onActive]);
 return <div className="lab-content"><div className="training-banner"><div><span className="eyebrow">TRAIN LOCALLY. LEARN OPENLY.</span><h2>让策略从经验中成长</h2><p>真实梯度更新与神经进化，全部在你的浏览器里完成</p></div><div className="network-glyph" aria-hidden="true">● <span>⌁</span> ● <span>⌁</span> ●</div></div>
 <div className="metrics-row"><Metric label="环境样本" value={fmt(total)} detail={`其中 ${fmt(metrics?.validationSteps??0)} 验证步`}/><Metric label={algorithm==='dqn'?'梯度更新':'完成代数'} value={fmt(algorithm==='dqn'?(metrics?.updates??0):(metrics?.generation??0))} detail={algorithm==='dqn'?'Adam · Huber loss':'锦标赛 · 精英 · 高斯变异'}/><Metric label={algorithm==='dqn'?'探索率 ε':'最佳训练分数'} value={algorithm==='dqn'?(metrics?.epsilon??1).toFixed(3):fmt(metrics?.bestScore??0)} detail={algorithm==='dqn'?'按样本数衰减':'训练分数不等于测试分数'}/><Metric label="验证集平均得分" value={metrics?.validationMean!=null?fmt(metrics.validationMean):'—'} detail="冻结权重 · ε = 0"/></div>
 <div className="experiment-layout"><Panel title="训练配置" eyebrow="EXPERIMENT SETUP" aside={<span className="badge">8 × 8</span>}><fieldset disabled={active} className="unstyled-fieldset"><div className="segmented full"><button className={algorithm==='dqn'?'selected':''} onClick={()=>{setAlgorithm('dqn');setBudget(100000);}}>DQN 强化学习</button><button className={algorithm==='ga'?'selected':''} onClick={()=>{setAlgorithm('ga');setBudget(500000);}}>GA 神经进化</button></div><div className="form-grid"><label className="field-label">训练种子<input aria-label="训练种子" type="number" min="0" value={seed} onChange={e=>setSeed(Number(e.target.value))}/></label><label className="field-label">资源预算<select aria-label="训练预算" value={budget} onChange={e=>setBudget(Number(e.target.value))}><option value={2000}>2,000 步 / 1 分钟 · 检查</option><option value={10000}>10,000 步 / 1 分钟 · 轻量</option><option value={100000}>100,000 步 / 1 分钟 · DQN 学习</option><option value={500000}>500,000 步 / 1 分钟 · GA 学习</option></select></label></div>{algorithm==='dqn'&&<label className="check-label"><input type="checkbox" checked={double} onChange={e=>setDouble(e.target.checked)}/>Double DQN <span className="badge">P5 对照变体</span></label>}<label className="check-label"><input type="checkbox" checked={obstacles} onChange={e=>setObstacles(e.target.checked)}/>障碍地图 <span className="badge">独立规则配置</span></label></fieldset><dl className="detail-list"><div><dt>网络</dt><dd>{algorithm==='dqn'?'12 → 64 → 64 → 3':'24 固定特征 → 3 动作 · 75 个基因'}</dd></div><div><dt>观察</dt><dd>相对食物 / 危险 / 射线 / 长度</dd></div><div><dt>后端</dt><dd>{algorithm==='dqn'?'TF.js CPU Worker':'JavaScript Worker'}</dd></div><div><dt>{algorithm==='dqn'?'预热 / 批量':'种群 / 每个体种子'}</dt><dd>{algorithm==='dqn'?'128 / 32':'16 / 3'}</dd></div><div><dt>每局预算</dt><dd>1,000 步 / 无食物 200 步</dd></div></dl><p className="notice">默认 v2 使用相对编码和即时碰撞过滤；DQN 使用距离奖励，GA 固定特征投影，按食物成绩进化 75 个输出系数。使用至少 3 个训练种子与独立测试衡量学习效果；快照展示单个训练环境。旧检查点按原设置恢复。</p><div className="button-row"><button className="primary" disabled={active} onClick={start}><Icon name="brain" size={17}/>开始训练</button>{active&&<><button onClick={()=>send(status==='paused'?'resume':'pause')}>{status==='paused'?'继续':'暂停'}</button><button onClick={()=>send('cancel')}>停止</button></>}</div><p className="status-line" role="status">{{idle:'准备就绪',initializing:'初始化引擎…',running:'训练中',paused:'已暂停，可继续或导出检查点',completed:'任务完成',cancelled:'已停止',error:'任务遇到错误'}[status]}{reason&&` · ${reason}`}</p><p className="fine-print">需要精确续训时，请先暂停并保存完整检查点，再停止任务。停止会立即释放 replay；自动预算结束会保留检查点。</p></Panel>
 <div className="training-right"><Panel title="学习曲线" eyebrow="MEASURED PROGRESS" aside={<span className="badge">训练均分</span>}><Sparkline values={metrics?.curve.map(point=>point.meanScore)??[]} label="训练得分曲线"/><div className="chart-axis"><span>0 SAMPLES</span><span>{fmt(total)} SAMPLES</span></div><div className="tiny-stats"><span>{algorithm==='dqn'?'最近损失':'代际中位适应度'}<strong>{algorithm==='dqn'?(metrics?.loss?.toFixed(5)??'—'):(metrics?.distribution?.median.toFixed(4)??'—')}</strong></span><span>实际用时<strong>{((metrics?.elapsedMs??0)/1000).toFixed(1)} s</strong></span><span>活跃张量<strong>{metrics?.tensors??0}</strong></span></div><p className="fine-print">采样数据有波动。验证与训练使用不同种子；测试集不参与选冠军。</p></Panel>
 <Panel title="抽样环境" eyebrow="TRAINING SNAPSHOT">{metrics?.snapshot?<div className="training-snapshot"><Board views={[{observation:metrics.snapshot,label:'训练抽样'}]}/><div><span className="badge">LIVE SAMPLE</span><p>当前食物 <strong>{metrics.snapshot.score}</strong></p><p>当前步数 <strong>{metrics.snapshot.steps}</strong></p><small className="muted">画面只是抽样，训练速度不依赖 FPS</small></div></div>:<div className="empty-state compact"><Icon name="brain" size={30}/><p>开始训练后观察真实环境</p></div>}</Panel></div></div>
 <Panel title="检查点与冻结评估" eyebrow="SAVE • RESTORE • TEST"><div className="checkpoint-grid"><div><h3>带走你的智能体</h3><p className="muted">完整检查点保留随机流、环境、优化器 / 种群与任务进度。推理模型仅保存冻结权重。</p><div className="button-row"><button disabled={!metrics||!['running','paused','completed'].includes(status)} onClick={()=>{saveMode.current='file';send('checkpoint');}}><Icon name="download" size={16}/>完整检查点</button><button disabled={!metrics||!['running','paused','completed'].includes(status)} onClick={()=>{saveMode.current='local';send('checkpoint');}}>本地保存</button><button disabled={!model} onClick={()=>model&&downloadFile('snake-frozen-model.json',JSON.stringify(model))}>导出推理模型</button></div>{saved.length>0&&<label className="field-label">载入本地检查点<select aria-label="本地检查点" disabled={active} defaultValue="" onChange={event=>{if(event.target.value)void loadRecord<TrainingCheckpoint>('checkpoint',event.target.value).then(value=>{if(value){setImported(value);setAlgorithm(value.algorithm);notify('已载入本地检查点，点击恢复继续');}}).catch(err=>notify(String(err)));}}><option value="">选择已保存记录</option>{saved.map(item=><option key={item.id} value={item.id}>{new Date(item.updatedAt).toLocaleString()} · {(item.bytes/1048576).toFixed(1)} MB</option>)}</select></label>}{imported&&<label className="check-label"><input type="checkbox" checked={extend} onChange={event=>setExtend(event.target.checked)}/>恢复时追加 {fmt(budget)} 步 / 1 分钟预算</label>}<div className="button-row"><button disabled={active} onClick={()=>input.current?.click()}><Icon name="upload" size={16}/>导入文件</button>{imported&&<button disabled={active} onClick={resumeCheckpoint}>恢复 {imported.algorithm.toUpperCase()} 检查点</button>}</div><input ref={input} className="sr-only" type="file" accept=".json,application/json" onChange={event=>void importFile(event)} aria-label="导入模型或检查点"/><p className="fine-print">导入版本化模型与检查点数据。模型上限 10 MB；完整检查点上限 128 MB。预计 replay 原始占用 {((metrics?.estimatedReplayBytes??(Math.min(20000,budget)*(12*8+6)))/1048576).toFixed(1)} MB（文件编码后更大）。</p></div><div><h3>独立测试集</h3><p className="muted">使用模型文件声明的测试种子（当前 {model?.seedSplit.testSeeds.length??100} 个）。关闭探索和更新，报告碰撞与实验截断。</p><button className="primary subtle" disabled={!model||active} onClick={evaluate}><Icon name="play" size={16}/>评估冻结模型 · {model?.seedSplit.testSeeds.length??100} 局</button>{model&&<p className="fine-print">{model.algorithm.toUpperCase()} · {fmt(model.provenance.samples)} 样本 · {model.game.width} × {model.game.height} 棋盘</p>}{evaluation&&<><p className="fine-print">数据划分：{evaluation.split} · {evaluation.episodes.length} 局 · 导入模型的来源声明由提供者负责</p><div className="tiny-stats"><span>平均食物<strong>{fmt(evaluation.meanScore)}</strong></span><span>填充率<strong>{(evaluation.meanFill*100).toFixed(1)}%</strong></span><span>碰撞率<strong>{(evaluation.collisionRate*100).toFixed(1)}%</strong></span></div><button onClick={()=>downloadFile('snake-model-evaluation.json',JSON.stringify(evaluation,null,2))}>导出评估结果</button></>}</div></div></Panel></div>;
}
